spring:
      application:
                  name: ecommerce
      data:
        mongodb:
          uri: <Your MongoDB URI>
          ssl:
            enabled: true
          database: model
          auto-index-creation: true
      main:
        allow-circular-references: true
      web:
        cors:
          allowed-origin-patterns: http://localhost:3000
          allowed-methods: GET,POST,PUT,DELETE
          allowed-headers: ["*"]
          allow-credentials: true
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
      mail:
        host: smtp.gmail.com
        port: 587
        username: <Your email address>
        password: <Email Pass key>
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true


#logging:
#  level:
#    root: INFO
#    com:
#      rituraj:
#        ecommerce: DEBUG
#    org:
#      hibernate: ERROR
#      springframework:
#        web : info
#        data:
#          mongodb:
#            core:
#              MongoTemplate: DEBUG
#              MongoClientFactoryBean: DEBUG



#CLOUDINARY
cloudinary:
  cloud-name: <Your Cloudinary cloud name>
  api-key: <Api key>
  api-secret: <Api Secret Key>

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        max-age: 360000
        path: /



